In [54]:
import numpy as np
import pandas as pd

In [55]:
pd.set_option('display.max_rows', None)

In [ ]:
df = pd.read_csv(r'D:\vs code projects\rental_analysis\data\interim\Gurugram\flat_house_data.csv')

In [57]:
df.sample(5)

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
1959,2 BHK Flat in Sector 66 Gurgaon,flat,ireo uptown,1.32,11442.0,1154.0,Super Built up area 1158(107.58 sq.m.),2,2,2,na,"Sector 66 Gurgaon, Gurgaon, Haryana",6.0,NaN,1 to 5 Year Old,"['Hub 66', 'Shiksha Bharti Public School', 'VI...",Residential apartment for sell.The property co...,"['1 Bed', '1 Light', '1 AC', 'No Chimney', 'No...","['Power Back-up', 'Intercom Facility', 'Lift(s...","['Green Area5 out of 5', 'Construction5 out of..."
2742,3 BHK Flat in Dharam Colony,flat,krishna appartment,0.35,3500.0,1000.0,Super Built up area 1000(92.9 sq.m.),3,3,1,na,"Dharam Colony, Gurgaon, Haryana",2.0,NaN,10+ Year Old,"['Palam triangle', 'Palam Vihar Vyapar kendra'...",Residential apartment for sell.Located on 2nd ...,"['3 Wardrobe', '3 Fan', '3 Light', 'No AC', 'N...",NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."
2726,2 BHK Flat in Sector 89 A Gurgaon,flat,adani aangan galleria,0.42,4941.0,850.0,Super Built up area 850(78.97 sq.m.),2,2,2,na,"Sector 89 A Gurgaon, Gurgaon, Haryana",3.0,NaN,1 to 5 Year Old,"['Indian Oil', 'Essar Petrol Pump', 'Garhi har...",Residential apartment for sell.Located in sect...,[],NaN,NaN
41,3 BHK Flat in Sector 65 Gurgaon,flat,m3m skycity,2.85,15590.0,1828.0,Super Built up area 1828(169.83 sq.m.),3,3,3,na,"Sector 65 Gurgaon, Gurgaon, Haryana",43.0,South,Dec 2024,"['Sector 55 Metro Station', 'Eros City Square'...",M3m skycity is one of the most popular destina...,"['1 Exhaust Fan', '1 AC', '1 Chimney', '1 Modu...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3838,2 BHK Flat in Sector 85 Gurgaon,flat,godrej air,1.30,14541.0,894.0,Super Built up area 1400(130.06 sq.m.)Carpet a...,2,2,3,na,"Sector 85 Gurgaon, Gurgaon, Haryana",30.0,NaN,Nov 2023,"['Sapphire 83 Mall', 'Sector 86 Road', 'Dwarka...",Sun facing spacious 2bhk in luxurious society ...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [58]:
df.shape

(3961, 20)

In [59]:
df.duplicated().sum()

np.int64(0)

In [60]:
df.isnull().sum()

property_name         0
property_type         0
society             570
price                20
price_per_sqft       20
area                 20
areaWithType          0
bedRoom               0
bathroom              0
balcony               0
additionalRoom        0
address              11
floorNum             21
facing             1177
agePossession         1
nearbyLocations     207
description           0
furnishDetails     1032
features            709
rating              450
dtype: int64

In [61]:
df.insert(loc=3,column='sector',value=df['property_name'].str.split('in').str.get(1).str.replace('Gurgaon','').str.strip())

In [62]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,...,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Sector 61 Gurgaon,flat,pioneer park,Sector 61,1.60,11594.0,1380.0,Carpet area: 1380 (128.21 sq.m.),2,2,...,servant room,"Sector 61 Gurgaon, Gurgaon, Haryana",21.0,NaN,1 to 5 Year Old,"['Sector 55-56 Rapid Metro', 'Hong Kong Bazaar...",Check out this 2 bhk flat for sale in pioneer ...,"['2 Wardrobe', 'No AC', 'No Bed', 'No Chimney'...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction3 out of..."
1,2 BHK Flat in Sector-33 Sohna,flat,godrej nature plus,Sector-33 Sohna,1.15,11558.0,995.0,Carpet area: 92.44,2,2,...,na,"Tower G 15th Floor, Sector-33 Sohna, Gurgaon, ...",15.0,NaN,Dec 2023,"['Signature Global Infinity Mall Sohna', 'Bads...",1.A one-Of-Its-Kind home with three pillars of...,"['3 Fan', '1 Exhaust Fan', '5 Light', 'No AC',...","['Intercom Facility', 'Lift(s)', 'Swimming Poo...",NaN
2,5 Bedroom House for sale in Sector 66 Gurgaon,house,emaar mgf marbella,Sector 66,NaN,NaN,NaN,Plot area 350(292.64 sq.m.),5,5,...,na,"Sector 66 Gurgaon, Gurgaon, Haryana",2.0,NaN,1 to 5 Year Old,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...",This property situated in marbella sector 65 g...,"['5 Fan', '1 Exhaust Fan', '6 Geyser', '1 Micr...","['Private Garden / Terrace', 'Maintenance Staf...","['Environment3 out of 5', 'Safety4 out of 5', ..."
3,4 BHK Flat in Sector 70A Gurgaon,flat,bptp astaire gardens,Sector 70A,1.60,8658.0,1848.0,Super Built up area 1848(171.68 sq.m.)Built Up...,4,4,...,"study room,others","H33, Sector 70A Gurgaon, Gurgaon, Haryana",1.0,NaN,1 to 5 Year Old,"['Sector 54 Chowk Metro Station', 'Airia Mall'...",Bptp astaire gardens is one of gurgaon's most ...,"['1 Fan', '1 Light', '2 Chimney', '4 AC', 'No ...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4 out of 5', 'Construction5 out of..."
4,3 BHK Flat in Sector 104 Gurgaon,flat,ats triumph,Sector 104,1.75,7641.0,2290.0,Super Built up area 2290(212.75 sq.m.)Carpet a...,3,4,...,"pooja room,study room,servant room,others","Sector 104 Gurgaon, Gurgaon, Haryana",12.0,North-West,1 to 5 Year Old,"['IFFCO Chowk Metro Station', 'The Esplanade M...","This 3 bhk flat is located in ats triumph, whi...","['4 Wardrobe', '7 Fan', '19 Light', '1 Chimney...","['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Green Area4 out of 5', 'Construction5 out of..."

In [63]:
df['sector'] = df['sector'].str.lower()

In [78]:
df['sector'] = df['sector'].str.replace('dharam colony','sector 12')
df['sector'] = df['sector'].str.replace('krishna colony','sector 7')
df['sector'] = df['sector'].str.replace('suncity','sector 54')
df['sector'] = df['sector'].str.replace('prem nagar','sector 13')
df['sector'] = df['sector'].str.replace('mg road','sector 28')
df['sector'] = df['sector'].str.replace('gandhi nagar','sector 28')
df['sector'] = df['sector'].str.replace('laxmi garden','sector 11')
df['sector'] = df['sector'].str.replace('shakti nagar','sector 11')
df['sector'] = df['sector'].str.replace('baldev nagar','sector 7')
df['sector'] = df['sector'].str.replace('shivpuri','sector 7')
df['sector'] = df['sector'].str.replace('garhi harsaru','sector 17')
df['sector'] = df['sector'].str.replace('imt manesar','manesar')
df['sector'] = df['sector'].str.replace('adarsh nagar','sector 12')
df['sector'] = df['sector'].str.replace('shivaji nagar','sector 11')
df['sector'] = df['sector'].str.replace('bhim nagar','sector 6')
df['sector'] = df['sector'].str.replace('madanpuri','sector 7')
df['sector'] = df['sector'].str.replace('saraswati vihar','sector 28')
df['sector'] = df['sector'].str.replace('arjun nagar','sector 8')
df['sector'] = df['sector'].str.replace('ravi nagar','sector 9')
df['sector'] = df['sector'].str.replace('vishnu garden','sector 105')
df['sector'] = df['sector'].str.replace('bhondsi','sector 11')
df['sector'] = df['sector'].str.replace('surya vihar','sector 21')
df['sector'] = df['sector'].str.replace('devilal colony','sector 9')
df['sector'] = df['sector'].str.replace('valley view estate','gwal pahari')
df['sector'] = df['sector'].str.replace('mehrauli  road','sector 14')
df['sector'] = df['sector'].str.replace('jyoti park','sector 7')
df['sector'] = df['sector'].str.replace('ansal plaza','sector 23')
df['sector'] = df['sector'].str.replace('dayanand colony','sector 6')
df['sector'] = df['sector'].str.replace('sushant lok phase 2','sector 55')
df['sector'] = df['sector'].str.replace('chakkarpur','sector 28')
df['sector'] = df['sector'].str.replace('greenwood city','sector 45')
df['sector'] = df['sector'].str.replace('subhash nagar','sector 12')
df['sector'] = df['sector'].str.replace('sohna road road','sohna road')
df['sector'] = df['sector'].str.replace('malibu town','sector 47')
df['sector'] = df['sector'].str.replace('surat nagar 1','sector 104')
df['sector'] = df['sector'].str.replace('new colony','sector 7')
df['sector'] = df['sector'].str.replace('mianwali colony','sector 12')
df['sector'] = df['sector'].str.replace('jacobpura','sector 12')
df['sector'] = df['sector'].str.replace('rajiv nagar','sector 13')
df['sector'] = df['sector'].str.replace('ashok vihar','sector 3')
df['sector'] = df['sector'].str.replace('dlf phase 1','sector 26')
df['sector'] = df['sector'].str.replace('nirvana country','sector 50')
df['sector'] = df['sector'].str.replace('palam vihar','sector 2')
df['sector'] = df['sector'].str.replace('dlf phase 2','sector 25')
df['sector'] = df['sector'].str.replace('sushant lok phase 1','sector 43')
df['sector'] = df['sector'].str.replace('laxman vihar','sector 4')
df['sector'] = df['sector'].str.replace('dlf phase 4','sector 28')
df['sector'] = df['sector'].str.replace('dlf phase 3','sector 24')
df['sector'] = df['sector'].str.replace('sushant lok phase 3','sector 57')
df['sector'] = df['sector'].str.replace('dlf phase 5','sector 43')
df['sector'] = df['sector'].str.replace('rajendra park','sector 105')
df['sector'] = df['sector'].str.replace('uppals southend','sector 49')
df['sector'] = df['sector'].str.replace('sohna','sohna road')
df['sector'] = df['sector'].str.replace('ashok vihar phase 3 extension','sector 5')
df['sector'] = df['sector'].str.replace('south city 1','sector 41')
df['sector'] = df['sector'].str.replace('ashok vihar phase 2','sector 5')
df['sector'] = df['sector'].str.replace('sohna road road','sohna road')

In [79]:
a = df['sector'].value_counts()[df['sector'].value_counts() >= 3]
df = df[df['sector'].isin(a.index)]

In [80]:
df['sector'].value_counts()

sector
sohna road                    175
sector 102                    113
sector 85                     110
sector 92                     104
sector 69                      94
sector 81                      90
sector 65                      90
sector 90                      90
sector 109                     88
sector 79                      80
sector 33                      74
sector 104                     73
sector 83                      69
sector 37d                     68
sector 43                      67
sector 86                      67
sector 95                      66
sector 50                      65
sector 89                      64
sector 2                       63
sector 107                     60
sector 108                     59
sector 56                      57
sector 48                      56
sector 70a                     54
sector 37c                     53
sector 70                      53
sector 84                      51
sector 26                      50
sector 4                       49
sector 67                      48
sector 49                      48
sector 28                      47
sector 66                      46
sector 103                     45
sector 25                      43
sector 113                     43
sector 61                      42
sector 82                      42
sector 7                       39
sector 106                     38
sector 12                      37
manesar                        33
sector 99a                     32
sector 54                      31
sector 68                      30
sector 77                      29
sector 72                      29
sector 71                      27
sector 24                      24
sector 57                      24
sector 112                     24
sector 3                       24
sector 105                     23
sector 88a                     23
sector 14                      23
sector 67a                     22
sector 111                     22
sector 11                      21
sector 22                      20
sector 82a                     20
sector 110                     19
sector 78                      19
sector 47                      19
gwal pahari                    18
sector 63a                     18
sector 74                      18
sector 91                      17
sector 62                      17
sector 99                      16
sector 60                      15
sector 63                      15
sector 52                      14
sector 55                      14
sector 53                      14
sector 76                      14
sector 46                      13
sector 6                       13
sector 23                      13
sector 9                       13
sector 36a                     13
sector 31                      12
sector 39                      12
sector 38                      12
sector 93                      12
sector 36                      11
sector 41                      11
sector 3 phase 3 extension     11
sector 9a                      11
sector 13                      10
sector 45                       9
sector 3 phase 2                9
sector 40                       8
sector 17                       8
sector 59                       8
sector 8                        8
dwarka expressway               8
sector 10a                      8
sector 51                       7
sector 58                       7
sector 5                        6
sector 21                       6
sector 1                        6
sector 15                       6
sector 80                       5
new sector 2                    5
sector 30                       5
new                             4
sector 73                       3
sector 88b                      3
sector 17a                      3
sector 17b                      3
sector 27                       3
Name: count, dtype: int64

In [81]:
df['sector'] = df['sector'].str.replace('sector 95a','sector 95')
df['sector'] = df['sector'].str.replace('sector 23a','sector 23')
df['sector'] = df['sector'].str.replace('sector 12a','sector 12')
df['sector'] = df['sector'].str.replace('sector 3a','sector 3')
df['sector'] = df['sector'].str.replace('sector 110 a','sector 110')
df['sector'] = df['sector'].str.replace('patel nagar','sector 15')
df['sector'] = df['sector'].str.replace('a block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('maruti kunj','sector 12')
df['sector'] = df['sector'].str.replace('b block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector-33 sohna road','sector 33')
df['sector'] = df['sector'].str.replace('sector 1 manesar','manesar')
df['sector'] = df['sector'].str.replace('sector 4 phase 2','sector 4')
df['sector'] = df['sector'].str.replace('sector 1a manesar','manesar')
df['sector'] = df['sector'].str.replace('c block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector 89 a','sector 89')
df['sector'] = df['sector'].str.replace('sector 2 extension','sector 2')
df['sector'] = df['sector'].str.replace('sector 36 sohna road','sector 36')

In [82]:
df['sector'].value_counts()

sector
sohna road                    175
sector 102                    113
sector 85                     110
sector 92                     104
sector 69                      94
sector 81                      90
sector 65                      90
sector 90                      90
sector 109                     88
sector 79                      80
sector 33                      74
sector 104                     73
sector 83                      69
sector 37d                     68
sector 43                      67
sector 86                      67
sector 95                      66
sector 50                      65
sector 89                      64
sector 2                       63
sector 107                     60
sector 108                     59
sector 56                      57
sector 48                      56
sector 70a                     54
sector 37c                     53
sector 70                      53
sector 84                      51
sector 26                      50
sector 4                       49
sector 67                      48
sector 49                      48
sector 28                      47
sector 66                      46
sector 103                     45
sector 25                      43
sector 113                     43
sector 61                      42
sector 82                      42
sector 7                       39
sector 106                     38
sector 12                      37
manesar                        33
sector 99a                     32
sector 54                      31
sector 68                      30
sector 77                      29
sector 72                      29
sector 71                      27
sector 24                      24
sector 57                      24
sector 112                     24
sector 3                       24
sector 105                     23
sector 88a                     23
sector 14                      23
sector 67a                     22
sector 111                     22
sector 11                      21
sector 22                      20
sector 82a                     20
sector 110                     19
sector 78                      19
sector 47                      19
gwal pahari                    18
sector 63a                     18
sector 74                      18
sector 91                      17
sector 62                      17
sector 99                      16
sector 60                      15
sector 63                      15
sector 52                      14
sector 55                      14
sector 53                      14
sector 76                      14
sector 46                      13
sector 6                       13
sector 23                      13
sector 9                       13
sector 36a                     13
sector 31                      12
sector 39                      12
sector 38                      12
sector 93                      12
sector 36                      11
sector 41                      11
sector 3 phase 3 extension     11
sector 9a                      11
sector 13                      10
sector 45                       9
sector 3 phase 2                9
sector 40                       8
sector 17                       8
sector 59                       8
sector 8                        8
dwarka expressway               8
sector 10a                      8
sector 51                       7
sector 58                       7
sector 5                        6
sector 21                       6
sector 1                        6
sector 15                       6
sector 80                       5
new sector 2                    5
sector 30                       5
new                             4
sector 73                       3
sector 88b                      3
sector 17a                      3
sector 17b                      3
sector 27                       3
Name: count, dtype: int64

In [83]:
df[df['sector'] == 'new']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,...,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
884,4 BHK Flat in New Gurgaon,flat,dlf 76,new,4.00,11428.0,3500.0,Carpet area: 3500 (325.16 sq.m.),4,4,...,"study room,servant room","New Gurgaon, Gurgaon, Haryana",4.0,NaN,Jun 2027,"['Shri Balaji Hospital and Trauma Center', 'S....",This lovely 4 bhk apartment/flat in new gurgao...,"['6 Wardrobe', '1 Fridge', '8 Fan', '1 Exhaust...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN
1406,2 BHK Flat in New Gurgaon,flat,green court,new,0.38,5507.0,690.0,Carpet area: 690 (64.1 sq.m.),2,2,...,na,"New Gurgaon, Gurgaon, Haryana",7.0,NaN,Under Construction,"['Ing bank ATM', 'Dcb bank ATM', 'Indus ind ba...",We are the proud owners of this 2 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...",NaN
2179,2 BHK Flat in New Gurgaon,flat,takshila heights sector 37 c,new,0.67,5583.0,1200.0,Super Built up area 1200(111.48 sq.m.),2,2,...,na,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,1 to 5 Year Old,"['Shri Balaji Hospital and Trauma Center', 'S....",Check out this 2 bhk apartment for sale in tak...,[],"['Lift(s)', 'Swimming Pool', 'Visitor Parking'...",NaN
2330,4 BHK Flat in New Gurgaon,flat,sare homes,new,0.85,4786.0,1776.0,Super Built up area 1776(165 sq.m.),4,4,...,na,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,5 to 10 Year Old,"['Columbia Asia Hospital', 'Apex Multi Special...",Located in the popular residential address of ...,[],NaN,NaN

In [84]:
df[df['sector'] == 'new sector 2']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,...,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
603,3 Bedroom House for sale in New Palam Vihar,house,NaN,new sector 2,1.00,8796.0,1137.0,Plot area 120(100.34 sq.m.)Built Up area: 120 ...,3,2,...,pooja room,"Q-148, New Palam Vihar, Phase-2, Near Royal Oa...",1.0,North,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","Ground and first floor, Ground floor: Ground f...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
1365,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.28,3166.0,884.0,Carpet area: 900 (83.61 sq.m.),2,1,...,others,"F 150/b, New Palam Vihar, Gurgaon, Haryana",2.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","2 bhk room with wooden coverd ,1 drawing room,...","['3 Wardrobe', '5 Light', '1 Chimney', '1 Modu...","['Water Storage', 'Park']","['Environment4 out of 5', 'Safety4 out of 5', ..."
2475,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.22,4400.0,500.0,Carpet area: 500 (46.45 sq.m.),2,2,...,na,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,0 to 1 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",Cctv surveillance are provided here. There is ...,"['3 Fan', '1 Exhaust Fan', '15 Light', '1 Modu...",NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."
3204,2 BHK Flat in New Palam Vihar,flat,ompee k s residency,new sector 2,1.60,26936.0,594.0,Carpet area: 66 (55.18 sq.m.),2,2,...,na,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",We are the proud owners of this 2 bhk apartmen...,NaN,NaN,"['Environment4 out of 5', 'Safety4 out of 5', ..."
3600,2 Bedroom House for sale in New Palam Vihar,house,my home,new sector 2,0.34,12592.0,270.0,Plot area 270(25.08 sq.m.),2,2,...,na,"Ez-19 A, New Palam Vihar, Gurgaon, Haryana",3.0,West,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",There are availability of various facilities l...,"['1 Wardrobe', '3 Fan', '6 Light', 'No AC', 'N...","['Water Storage', 'Park', 'Visitor Parking']","['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [85]:
df.loc[[311,1072,1486,3040,3875],'sector'] = 'sector 110'

In [86]:
# features to drop -> property_name, address, description, rating
df.drop(columns=['property_name', 'address', 'description', 'rating'],inplace=True)

In [89]:
df.to_csv(r'D:\vs code projects\rental_analysis\data\interim\Gurugram\flat_house_data_cleaned.csv',index=False)