In [94]:
import numpy as np
import pandas as pd

In [95]:
pd.set_option('display.max_rows', None)

In [96]:
flats=pd.read_csv(r'D:\vs code projects\rental_analysis\data\interim\Gurugram\Flats\flats_cleaned.csv')
houses=pd.read_csv(r'D:\vs code projects\rental_analysis\data\interim\Gurugram\independent_houses\houses_cleaned.csv')

In [97]:
df=pd.concat([flats,houses],ignore_index=True)

In [98]:
df=df.sample(df.shape[0],ignore_index=True)

In [99]:
df.sample(5)

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
951,3 BHK Flat in Sector 69 Gurgaon,flat,tulip violet,1.60,10139.0,1578.0,Super Built up area 1578(146.6 sq.m.),3,3,2,pooja room,"Sector 69 Gurgaon, Gurgaon, Haryana",0.0,South-West,1 to 5 Year Old,"['Airia Mall Sector 68', 'Southern Peripheral ...",3 bhk flat on ground floor. Located in the pop...,"['1 Modular Kitchen', 'No AC', 'No Bed', 'No C...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction4 out of..."
1761,2 BHK Flat in Sector 81 Gurgaon,flat,vipul lavanya,0.75,5966.0,1257.0,Carpet area: 1257 (116.78 sq.m.),2,2,2,na,"T 10/ 702, Sector 81 Gurgaon, Gurgaon, Haryana",7.0,NaN,5 to 10 Year Old,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",The property is garden facing. Also the whole ...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Lift(s)', 'Maintena...","['Green Area5 out of 5', 'Construction4.5 out ..."
2431,3 BHK Flat in Sector 68 Gurgaon,flat,pareena mi casa,1.85,9310.0,1987.0,Super Built up area 1987(184.6 sq.m.),3,3,3+,na,"Sector 68 Gurgaon, Gurgaon, Haryana",13.0,NaN,Under Construction,"['Sector 55-56 Metro Station', 'Airia Mall', '...",Pareena mi casa is one of the most popular des...,[],NaN,"['Safety5 out of 5', 'Lifestyle4 out of 5', 'E..."
1485,2 BHK Flat in Sector-33 Sohna,flat,godrej nature plus,1.08,13126.0,823.0,Carpet area: 76.44,2,2,3,na,"Sector-33 Sohna, Gurgaon, Haryana",8.0,NaN,Jan 2024,"['Signature Global Infinity Mall Sohna', 'Bads...","Full of amenities ,lush green gardens swimming...",NaN,NaN,NaN
3414,3 BHK Flat in Sector 37C Gurgaon,flat,ild grand,1.35,7142.0,1890.0,Built Up area: 1820 (169.08 sq.m.),3,3,0,na,"Lower Floor With Extra Terrace, Sector 37C Gur...",1.0,NaN,Within 6 months,"['The Esplanade Mall', 'Dwarka Expy, Sector 88...","3 bath, semi-Furnished, 1st floor (Of 24), ild...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."

In [100]:
df.shape

(3961, 20)

In [101]:
df.duplicated().sum()

np.int64(0)

In [102]:
df.isnull().sum()

property_name         0
property_type         0
society               1
price                20
price_per_sqft       20
area                 20
areaWithType          0
bedRoom               0
bathroom              0
balcony               0
additionalRoom        0
address              11
floorNum             21
facing             1177
agePossession         1
nearbyLocations     207
description           0
furnishDetails     1032
features            709
rating              450
dtype: int64

In [103]:
df.insert(loc=3,column='sector',value=df['property_name'].str.split('in').str.get(1).str.replace('Gurgaon','').str.strip())

In [104]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,...,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Sector 79 Gurgaon,flat,supertech araville,Sector 79,0.71,5522.0,1286.0,Built Up area: 1295 (120.31 sq.m.),2,2,...,na,"E906, Sector-79, Sector 79 Gurgaon, Gurgaon, H...",9.0,NaN,Under Construction,"['Petrol Pump Indian Oil', 'Petrol Pump', 'Rao...",Construction linked booking. First holder. Pai...,[],NaN,"['Environment4 out of 5', 'Lifestyle3 out of 5..."
1,18 Bedroom House for sale in Suncity,house,independent,Suncity,5.50,38194.0,1440.0,Plot area 160(133.78 sq.m.),18,18,...,servant room,"11111, Suncity, Gurgaon, Haryana",4.0,South-West,1 to 5 Year Old,"['Sector 54 chowk metro station', 'Sector metr...",18 bed room newly built up in 160 yds plot is ...,"['1 Water Purifier', '22 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'High Ceiling...","['Environment5 out of 5', 'Safety5 out of 5', ..."
2,2 BHK Flat in Sector 79 Gurgaon,flat,supertech araville,Sector 79,0.95,6209.0,1530.0,Super Built up area 1530(142.14 sq.m.),2,2,...,study room,"Sector 79 Gurgaon, Gurgaon, Haryana",7.0,North-East,0 to 1 Year Old,"['Petrol Pump Indian Oil', 'Petrol Pump', 'Rao...","Right next to the new golf course road, m3m an...","['1 Fan', '1 Geyser', '1 Light', 'No AC', 'No ...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Lifestyle3 out of 5..."
3,3 BHK Flat in Sector 60 Gurgaon,flat,ireo skyon,Sector 60,2.65,13125.0,2019.0,Super Built up area 2045(189.99 sq.m.)Built Up...,3,4,...,servant room,"Block D, Sector 60 Gurgaon, Gurgaon, Haryana",7.0,North-East,5 to 10 Year Old,"['Sector 55-56 Metro', 'Golf Course Extension'...",Ireo skyon all sizes available at best price g...,"['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '4 Ge...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction5 out of..."
4,2 BHK Flat in Sohna Road,flat,bhemerlei,Sohna Road,0.69,5100.0,1353.0,Built Up area: 1350 (125.42 sq.m.),2,2,...,na,"Sohna Road, Gurgaon, Haryana",3.0,NaN,Under Construction,"['Rajiv Chowk Mosque', 'Standard chartered ATM...",Interested to sell residential apartment. Want...,[],NaN,NaN

In [105]:
df['sector'] = df['sector'].str.lower()

In [106]:
df['sector'] = df['sector'].str.replace('dharam colony','sector 12')
df['sector'] = df['sector'].str.replace('krishna colony','sector 7')
df['sector'] = df['sector'].str.replace('suncity','sector 54')
df['sector'] = df['sector'].str.replace('prem nagar','sector 13')
df['sector'] = df['sector'].str.replace('mg road','sector 28')
df['sector'] = df['sector'].str.replace('gandhi nagar','sector 28')
df['sector'] = df['sector'].str.replace('laxmi garden','sector 11')
df['sector'] = df['sector'].str.replace('shakti nagar','sector 11')
df['sector'] = df['sector'].str.replace('baldev nagar','sector 7')
df['sector'] = df['sector'].str.replace('shivpuri','sector 7')
df['sector'] = df['sector'].str.replace('garhi harsaru','sector 17')
df['sector'] = df['sector'].str.replace('imt manesar','manesar')
df['sector'] = df['sector'].str.replace('adarsh nagar','sector 12')
df['sector'] = df['sector'].str.replace('shivaji nagar','sector 11')
df['sector'] = df['sector'].str.replace('bhim nagar','sector 6')
df['sector'] = df['sector'].str.replace('madanpuri','sector 7')
df['sector'] = df['sector'].str.replace('saraswati vihar','sector 28')
df['sector'] = df['sector'].str.replace('arjun nagar','sector 8')
df['sector'] = df['sector'].str.replace('ravi nagar','sector 9')
df['sector'] = df['sector'].str.replace('vishnu garden','sector 105')
df['sector'] = df['sector'].str.replace('bhondsi','sector 11')
df['sector'] = df['sector'].str.replace('surya vihar','sector 21')
df['sector'] = df['sector'].str.replace('devilal colony','sector 9')
df['sector'] = df['sector'].str.replace('valley view estate','gwal pahari')
df['sector'] = df['sector'].str.replace('mehrauli  road','sector 14')
df['sector'] = df['sector'].str.replace('jyoti park','sector 7')
df['sector'] = df['sector'].str.replace('ansal plaza','sector 23')
df['sector'] = df['sector'].str.replace('dayanand colony','sector 6')
df['sector'] = df['sector'].str.replace('sushant lok phase 2','sector 55')
df['sector'] = df['sector'].str.replace('chakkarpur','sector 28')
df['sector'] = df['sector'].str.replace('greenwood city','sector 45')
df['sector'] = df['sector'].str.replace('subhash nagar','sector 12')
df['sector'] = df['sector'].str.replace('sohna road road','sohna road')
df['sector'] = df['sector'].str.replace('malibu town','sector 47')
df['sector'] = df['sector'].str.replace('surat nagar 1','sector 104')
df['sector'] = df['sector'].str.replace('new colony','sector 7')
df['sector'] = df['sector'].str.replace('mianwali colony','sector 12')
df['sector'] = df['sector'].str.replace('jacobpura','sector 12')
df['sector'] = df['sector'].str.replace('rajiv nagar','sector 13')
df['sector'] = df['sector'].str.replace('ashok vihar','sector 3')
df['sector'] = df['sector'].str.replace('dlf phase 1','sector 26')
df['sector'] = df['sector'].str.replace('nirvana country','sector 50')
df['sector'] = df['sector'].str.replace('palam vihar','sector 2')
df['sector'] = df['sector'].str.replace('dlf phase 2','sector 25')
df['sector'] = df['sector'].str.replace('sushant lok phase 1','sector 43')
df['sector'] = df['sector'].str.replace('laxman vihar','sector 4')
df['sector'] = df['sector'].str.replace('dlf phase 4','sector 28')
df['sector'] = df['sector'].str.replace('dlf phase 3','sector 24')
df['sector'] = df['sector'].str.replace('sushant lok phase 3','sector 57')
df['sector'] = df['sector'].str.replace('dlf phase 5','sector 43')
df['sector'] = df['sector'].str.replace('rajendra park','sector 105')
df['sector'] = df['sector'].str.replace('uppals southend','sector 49')
df['sector'] = df['sector'].str.replace('sohna','sohna road')
df['sector'] = df['sector'].str.replace('ashok vihar phase 3 extension','sector 5')
df['sector'] = df['sector'].str.replace('south city 1','sector 41')
df['sector'] = df['sector'].str.replace('ashok vihar phase 2','sector 5')
df['sector'] = df['sector'].str.replace('sohna road road','sohna road')

In [107]:
a = df['sector'].value_counts()[df['sector'].value_counts() >= 3]
df = df[df['sector'].isin(a.index)]

In [108]:
df['sector'].value_counts()

sector
sohna road                    175
sector 102                    113
sector 85                     110
sector 92                     104
sector 69                      94
sector 90                      90
sector 65                      90
sector 81                      90
sector 109                     88
sector 79                      80
sector 104                     73
sector 83                      69
sector 37d                     68
sector 86                      67
sector 50                      65
sector 107                     60
sector 108                     59
sector 56                      57
sector 95                      57
sector 48                      56
sector 89                      56
sector 2                       55
sector 70a                     54
sector 43                      53
sector 70                      53
sector 37c                     53
sector 84                      51
sector-33 sohna road           51
sector 26                      50
sector 49                      48
sector 67                      48
sector 28                      47
sector 66                      46
sector 103                     45
sector 113                     43
sector 25                      43
sector 61                      42
sector 82                      42
sector 7                       39
sector 106                     38
sector 4                       36
sector 99a                     32
sector 54                      31
sector 68                      30
sector 12                      30
sector 77                      29
sector 72                      29
sector 71                      27
sector 112                     24
sector 57                      24
sector 24                      24
sector 88a                     23
sector 33                      23
sector 105                     23
sector 14                      23
sector 67a                     22
sector 111                     22
sector 11                      21
sector 3                       20
sector 22                      20
sector 82a                     20
sector 78                      19
sector 47                      19
gwal pahari                    18
sector 74                      18
sector 63a                     18
sector 62                      17
sector 91                      17
sector 99                      16
sector 110                     16
sector 60                      15
sector 63                      15
sector 1 manesar               14
sector 55                      14
sector 76                      14
sector 52                      14
sector 53                      14
sector 6                       13
sector 4 phase 2               13
sector 9                       13
sector 36a                     13
sector 46                      13
sector 31                      12
sector 93                      12
sector 39                      12
sector 38                      12
sector 3 phase 3 extension     11
sector 41                      11
sector 9a                      11
sector 13                      10
sector 1a manesar              10
sector 95a                      9
sector 45                       9
sector 3 phase 2                9
manesar                         9
sector 2 extension              8
c block sector 43               8
sector 89 a                     8
sector 10a                      8
sector 23                       8
sector 8                        8
sector 17                       8
dwarka expressway               8
sector 59                       8
sector 40                       8
sector 58                       7
sector 51                       7
sector 36 sohna road            7
sector 21                       6
sector 5                        6
sector 1                        6
sector 80                       5
sector 23a                      5
sector 30                       5
new sector 2                    5
sector 3a                       4
sector 12a                      4
new                             4
sector 36                       4
sector 15                       3
sector 73                       3
patel nagar                     3
sector 17a                      3
b block sector 43               3
maruti kunj                     3
a block sector 43               3
sector 88b                      3
sector 27                       3
sector 110 a                    3
sector 17b                      3
Name: count, dtype: int64

In [109]:
df['sector'] = df['sector'].str.replace('sector 95a','sector 95')
df['sector'] = df['sector'].str.replace('sector 23a','sector 23')
df['sector'] = df['sector'].str.replace('sector 12a','sector 12')
df['sector'] = df['sector'].str.replace('sector 3a','sector 3')
df['sector'] = df['sector'].str.replace('sector 110 a','sector 110')
df['sector'] = df['sector'].str.replace('patel nagar','sector 15')
df['sector'] = df['sector'].str.replace('a block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('maruti kunj','sector 12')
df['sector'] = df['sector'].str.replace('b block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector-33 sohna road','sector 33')
df['sector'] = df['sector'].str.replace('sector 1 manesar','manesar')
df['sector'] = df['sector'].str.replace('sector 4 phase 2','sector 4')
df['sector'] = df['sector'].str.replace('sector 1a manesar','manesar')
df['sector'] = df['sector'].str.replace('c block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector 89 a','sector 89')
df['sector'] = df['sector'].str.replace('sector 2 extension','sector 2')
df['sector'] = df['sector'].str.replace('sector 36 sohna road','sector 36')

In [110]:
df['sector'].value_counts()

sector
sohna road                    175
sector 102                    113
sector 85                     110
sector 92                     104
sector 69                      94
sector 90                      90
sector 65                      90
sector 81                      90
sector 109                     88
sector 79                      80
sector 33                      74
sector 104                     73
sector 83                      69
sector 37d                     68
sector 43                      67
sector 86                      67
sector 95                      66
sector 50                      65
sector 89                      64
sector 2                       63
sector 107                     60
sector 108                     59
sector 56                      57
sector 48                      56
sector 70a                     54
sector 70                      53
sector 37c                     53
sector 84                      51
sector 26                      50
sector 4                       49
sector 49                      48
sector 67                      48
sector 28                      47
sector 66                      46
sector 103                     45
sector 113                     43
sector 25                      43
sector 61                      42
sector 82                      42
sector 7                       39
sector 106                     38
sector 12                      37
manesar                        33
sector 99a                     32
sector 54                      31
sector 68                      30
sector 77                      29
sector 72                      29
sector 71                      27
sector 3                       24
sector 112                     24
sector 57                      24
sector 24                      24
sector 88a                     23
sector 105                     23
sector 14                      23
sector 67a                     22
sector 111                     22
sector 11                      21
sector 22                      20
sector 82a                     20
sector 78                      19
sector 47                      19
sector 110                     19
gwal pahari                    18
sector 74                      18
sector 63a                     18
sector 62                      17
sector 91                      17
sector 99                      16
sector 60                      15
sector 63                      15
sector 55                      14
sector 76                      14
sector 52                      14
sector 53                      14
sector 6                       13
sector 9                       13
sector 23                      13
sector 36a                     13
sector 46                      13
sector 31                      12
sector 93                      12
sector 39                      12
sector 38                      12
sector 3 phase 3 extension     11
sector 41                      11
sector 9a                      11
sector 36                      11
sector 13                      10
sector 45                       9
sector 3 phase 2                9
sector 10a                      8
sector 8                        8
sector 17                       8
dwarka expressway               8
sector 59                       8
sector 40                       8
sector 58                       7
sector 51                       7
sector 15                       6
sector 21                       6
sector 5                        6
sector 1                        6
sector 80                       5
sector 30                       5
new sector 2                    5
new                             4
sector 73                       3
sector 17a                      3
sector 88b                      3
sector 27                       3
sector 17b                      3
Name: count, dtype: int64

In [111]:
df[df['sector'] == 'new']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,...,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
820,2 BHK Flat in New Gurgaon,flat,green court,new,0.38,5507.0,690.0,Carpet area: 690 (64.1 sq.m.),2,2,...,na,"New Gurgaon, Gurgaon, Haryana",7.0,NaN,Under Construction,"['Ing bank ATM', 'Dcb bank ATM', 'Indus ind ba...",We are the proud owners of this 2 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...",NaN
2415,4 BHK Flat in New Gurgaon,flat,sare homes,new,0.85,4786.0,1776.0,Super Built up area 1776(165 sq.m.),4,4,...,na,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,5 to 10 Year Old,"['Columbia Asia Hospital', 'Apex Multi Special...",Located in the popular residential address of ...,[],NaN,NaN
2771,2 BHK Flat in New Gurgaon,flat,takshila heights sector 37 c,new,0.67,5583.0,1200.0,Super Built up area 1200(111.48 sq.m.),2,2,...,na,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,1 to 5 Year Old,"['Shri Balaji Hospital and Trauma Center', 'S....",Check out this 2 bhk apartment for sale in tak...,[],"['Lift(s)', 'Swimming Pool', 'Visitor Parking'...",NaN
3705,4 BHK Flat in New Gurgaon,flat,dlf 76,new,4.00,11428.0,3500.0,Carpet area: 3500 (325.16 sq.m.),4,4,...,"study room,servant room","New Gurgaon, Gurgaon, Haryana",4.0,NaN,Jun 2027,"['Shri Balaji Hospital and Trauma Center', 'S....",This lovely 4 bhk apartment/flat in new gurgao...,"['6 Wardrobe', '1 Fridge', '8 Fan', '1 Exhaust...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN

In [112]:
df[df['sector'] == 'new sector 2']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,...,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
636,2 BHK Flat in New Palam Vihar,flat,ompee k s residency,new sector 2,1.60,26936.0,594.0,Carpet area: 66 (55.18 sq.m.),2,2,...,na,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",We are the proud owners of this 2 bhk apartmen...,NaN,NaN,"['Environment4 out of 5', 'Safety4 out of 5', ..."
924,3 Bedroom House for sale in New Palam Vihar,house,independent,new sector 2,1.00,8796.0,1137.0,Plot area 120(100.34 sq.m.)Built Up area: 120 ...,3,2,...,pooja room,"Q-148, New Palam Vihar, Phase-2, Near Royal Oa...",1.0,North,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","Ground and first floor, Ground floor: Ground f...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
3360,2 Bedroom House for sale in New Palam Vihar,house,my home,new sector 2,0.34,12592.0,270.0,Plot area 270(25.08 sq.m.),2,2,...,na,"Ez-19 A, New Palam Vihar, Gurgaon, Haryana",3.0,West,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",There are availability of various facilities l...,"['1 Wardrobe', '3 Fan', '6 Light', 'No AC', 'N...","['Water Storage', 'Park', 'Visitor Parking']","['Environment4 out of 5', 'Lifestyle4 out of 5..."
3396,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.22,4400.0,500.0,Carpet area: 500 (46.45 sq.m.),2,2,...,na,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,0 to 1 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",Cctv surveillance are provided here. There is ...,"['3 Fan', '1 Exhaust Fan', '15 Light', '1 Modu...",NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."
3488,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.28,3166.0,884.0,Carpet area: 900 (83.61 sq.m.),2,1,...,others,"F 150/b, New Palam Vihar, Gurgaon, Haryana",2.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","2 bhk room with wooden coverd ,1 drawing room,...","['3 Wardrobe', '5 Light', '1 Chimney', '1 Modu...","['Water Storage', 'Park']","['Environment4 out of 5', 'Safety4 out of 5', ..."

In [117]:
# features to drop -> property_name, address, description, rating
df.drop(columns=['property_name', 'address', 'description', 'rating'],inplace=True)

In [118]:
df.to_csv(r'D:\vs code projects\rental_analysis\data\interim\Gurugram\flat_house_data.csv',index=False)